import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  vestigefiSidebar: [{ type: "autogenerated", dirName: "vestigefi" }],
  rugninjaSidebar: [{ type: "autogenerated", dirName: "rugninja" }],
  tamequestSidebar: [{ type: "autogenerated", dirName: "tamequest" }],
  chainuiSidebar: [{ type: "autogenerated", dirName: "chainui" }],
};

export default sidebars;
